/**
 * Learning — RECOMPUTE the rules from field outcomes → `learning/rules/rules.json`
 * (+ a readable report `learning/analysis/report.md`). The next scoring run applies them. Loop closed.
 *
 *   npm run learn                         # reads data/outcomes.jsonl
 *   npm run learn -- demo/outcomes.sample.jsonl
 *
 * PHILOSOPHY — the loop REFINES, it does not decide:
 *  • Small-N shrinkage: every delta is multiplied by a confidence n/(n+prior). Two outcomes move almost
 *    nothing; it takes volume to shift a baseline. That is the guard against learning from an anecdote.
 *  • Tight bounds: |value delta| ≤ 15, signal multiplier ∈ [0.5, 1.5]. The human rule stays the floor.
 *  • Two things are learned: (1) which TRADES really convert → nudge their value baseline;
 *    (2) which free SIGNALS predict a sale → scale their bonus.
 */
import { readFile, writeFile, mkdir } from "node:fs/promises"
import { join, dirname } from "node:path"
import { fileURLToPath } from "node:url"
import { OUTCOME_WEIGHT, type Outcome, type RulesFile } from "./types.ts"
import { RULES_PATH } from "./rules.ts"

// calibration constants — the caution is deliberate
const VALUE_SCALE = 30 // value points per unit of conversion lift (lift 0.3 → +9 before shrinkage)
const IND_PRIOR = 8 // outcomes needed to reach 50% confidence on a trade
const IND_CAP = 15
const SIG_SCALE = 1.0
const SIG_PRIOR = 5
const SIG_MIN = 0.5
const SIG_MAX = 1.5

const SIGNAL_KEYS = ["gallery", "quoteCta", "social", "premium", "multiSite", "ecommerce", "booking", "blog"] as const

const clamp = (n: number, lo: number, hi: number) => Math.max(lo, Math.min(hi, n))
const mean = (xs: number[]) => (xs.length ? xs.reduce((a, b) => a + b, 0) / xs.length : 0)
const success = (o: Outcome) => OUTCOME_WEIGHT[o.outcome] ?? 0

type TradeEvidence = { industry: string; n: number; rate: number; conf: number; valueDelta: number }
type SignalEvidence = { signal: string; nWith: number; nWithout: number; lift: number; conf: number; mult: number }

/** The PURE computation (no I/O, unit-tested): outcomes → bounded, shrunk rules. */
export function buildRules(outcomes: Outcome[], now: string): RulesFile {
  const file: RulesFile = { updatedAt: now, totalOutcomes: outcomes.length, industries: {}, signals: {} }
  if (outcomes.length === 0) return file
  const globalRate = mean(outcomes.map(success))

  // (1) TRADES: real conversion vs the mean → value delta (bounded, shrunk)
  const byTrade = new Map<string, Outcome[]>()
  for (const o of outcomes) byTrade.set(o.industry, [...(byTrade.get(o.industry) ?? []), o])
  const trades: TradeEvidence[] = []
  for (const [industry, os] of byTrade) {
    const n = os.length
    const rate = mean(os.map(success))
    const conf = n / (n + IND_PRIOR)
    const valueDelta = clamp(Math.round((rate - globalRate) * VALUE_SCALE * conf), -IND_CAP, IND_CAP)
    if (valueDelta !== 0) file.industries![industry] = { value: valueDelta }
    trades.push({ industry, n, rate: +rate.toFixed(2), conf: +conf.toFixed(2), valueDelta })
  }

  // (2) SIGNALS: lift (present vs absent) → bonus multiplier (bounded, shrunk)
  const signals: SignalEvidence[] = []
  for (const k of SIGNAL_KEYS) {
    const withS = outcomes.filter((o) => o.signals?.[k])
    const without = outcomes.filter((o) => !o.signals?.[k])
    if (!withS.length || !without.length) continue // no contrast → nothing can be said
    const lift = mean(withS.map(success)) - mean(without.map(success))
    const nMin = Math.min(withS.length, without.length)
    const conf = nMin / (nMin + SIG_PRIOR)
    const mult = clamp(1 + lift * SIG_SCALE * conf, SIG_MIN, SIG_MAX)
    if (Math.abs(mult - 1) > 0.01) file.signals![k] = +mult.toFixed(2)
    signals.push({ signal: k, nWith: withS.length, nWithout: without.length, lift: +lift.toFixed(2), conf: +conf.toFixed(2), mult: +mult.toFixed(2) })
  }

  file.evidence = { globalRate: +globalRate.toFixed(2), trades, signals }
  return file
}

function renderReport(file: RulesFile): string {
  const ev = file.evidence as { globalRate: number; trades: TradeEvidence[]; signals: SignalEvidence[] } | undefined
  const L = ["# Learning — calibration report", "", `> Generated by \`npm run learn\` on ${file.updatedAt}. Do not edit by hand.`, ""]
  L.push(`**Outcomes analysed: ${file.totalOutcomes}.**${file.totalOutcomes < 10 ? " Small sample → deliberately tiny deltas (shrinkage)." : ""}`, "")
  if (!ev) return L.join("\n") + "\nNo outcome yet: the scoring runs on its human baselines.\n"
  L.push(`Global success rate: **${ev.globalRate}** (won = 1 · meeting = .6 · reply = .3 · sent/lost = 0).`, "")
  L.push("## Trades — learned value delta", "", "| trade | n | rate | confidence | Δ value |", "|---|---:|---:|---:|---:|")
  for (const r of ev.trades) L.push(`| ${r.industry} | ${r.n} | ${r.rate} | ${r.conf} | ${r.valueDelta >= 0 ? "+" : ""}${r.valueDelta} |`)
  L.push("", "## Free signals — learned bonus multiplier", "", "| signal | n with | n without | lift | confidence | × |", "|---|---:|---:|---:|---:|---:|")
  for (const r of ev.signals) L.push(`| ${r.signal} | ${r.nWith} | ${r.nWithout} | ${r.lift >= 0 ? "+" : ""}${r.lift} | ${r.conf} | ${r.mult} |`)
  return L.join("\n") + "\n"
}

// --- CLI ---
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const source = process.argv[2] || join("data", "outcomes.jsonl")
  let outcomes: Outcome[] = []
  try {
    outcomes = (await readFile(source, "utf8")).split("\n").filter(Boolean).map((l) => JSON.parse(l) as Outcome)
  } catch {
    /* no outcome yet → empty rules */
  }
  const file = buildRules(outcomes, new Date().toISOString())
  const reportPath = join("learning", "analysis", "report.md")
  await mkdir(dirname(RULES_PATH()), { recursive: true })
  await mkdir(dirname(reportPath), { recursive: true })
  await writeFile(RULES_PATH(), JSON.stringify(file, null, 2) + "\n")
  await writeFile(reportPath, renderReport(file))
  console.log(`✓ rules recomputed from ${outcomes.length} outcome(s) (${source}) → ${RULES_PATH()}`)
  console.log(`  ${Object.keys(file.industries ?? {}).length} trade(s) and ${Object.keys(file.signals ?? {}).length} signal(s) adjusted · report: ${reportPath}`)
}
